### ISSUE TITLE
ValueError : Cannot create group in read only mode.

### ISSUE THREAD

**Issue by krishna1994** [mtobeiyf/keras-flask-deploy-webapp#11]
Hi @mtobeiyf ,

While using my own trained model, I am facing this issue:
runfile('C:/Users/Singhkri/Videos/keras-flask-deploy-webapp-master/app.py', wdir='C:/Users/Singhkri/Videos/keras-flask-deploy-webapp-master')
Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-1-2cd7bb31bf04>", line 1, in <module>
    runfile('C:/Users/Singhkri/Videos/keras-flask-deploy-webapp-master/app.py', wdir='C:/Users/Singhkri/Videos/keras-flask-deploy-webapp-master')

  File "C:\Users\Singhkri\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\Singhkri\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Singhkri/Videos/keras-flask-deploy-webapp-master/app.py", line 17, in <module>
    model = load_model('models/model.h5')

  File "C:\Users\Singhkri\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)

  File "C:\Users\Singhkri\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\saving.py", line 221, in _deserialize_model
    model_config = f['model_config']

  File "C:\Users\Singhkri\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\utils\io_utils.py", line 302, in __getitem__
    raise ValueError('Cannot create group in read only mode.')

ValueError: Cannot create group in read only mode.

It would be helpful if you can help in sorting out this.

**Comment by mtobeiyf** [comment]
You need to define your model first before loading the weights, because your 'h5' file does not include the definition of your model.
See https://stackoverflow.com/a/53214077
