### ISSUE TITLE
ValueError has detected

### ISSUE THREAD

**Issue by wurangbo** [mtobeiyf/keras-flask-deploy-webapp#9]
hi, 
When I run the app, I got the error as below,
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\download\keras-flask-deploy-webapp-master\app.py", line 75, in upload
    preds = model_predict(file_path, model)
  File "C:\download\keras-flask-deploy-webapp-master\app.py", line 52, in model_predict
    preds = model.predict(x)
  File "C:\download\keras-flask-deploy-webapp-master\venv\lib\site-packages\keras\engine\training.py", line 1164, in predict
    self._make_predict_function()
  File "C:\download\keras-flask-deploy-webapp-master\venv\lib\site-packages\keras\engine\training.py", line 554, in _make_predict_function
    **kwargs)
  File "C:\download\keras-flask-deploy-webapp-master\venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 2744, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "C:\download\keras-flask-deploy-webapp-master\venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 2546, in __init__
    with tf.control_dependencies(self.outputs):
  File "C:\download\keras-flask-deploy-webapp-master\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 5004, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "C:\download\keras-flask-deploy-webapp-master\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 4543, in control_dependencies
    c = self.as_graph_element(c)
  File "C:\download\keras-flask-deploy-webapp-master\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3490, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\download\keras-flask-deploy-webapp-master\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3569, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("fc1000/Softmax:0", shape=(?, 1000), dtype=float32) is not an element of this graph.

**Comment by mtobeiyf** [comment]
Not sure how you ran the code. Check the versions of your libraries.
And, this might be helpful: https://github.com/keras-team/keras/issues/2397

**Comment by mark-nakachon** [comment]
hi, 
I am getting this error when I am running python3 app.py and even my Keras(version) is 2.2.4 and Tensor flow version is 1.11.0

  model = keras.models.load_model(MODEL_PATH)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/sequential.py", line 300, in from_config
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 1109, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/convolutional.py", line 490, in __init__
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/convolutional.py", line 117, in __init__
    self.kernel_initializer = initializers.get(kernel_initializer)
  File "/usr/local/lib/python3.6/dist-packages/keras/initializers.py", line 508, in get
    return deserialize(identifier)
  File "/usr/local/lib/python3.6/dist-packages/keras/initializers.py", line 503, in deserialize
    printable_module_name='initializer')
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown initializer: GlorotUniform

**Comment by mtobeiyf** [comment]
Seems keras could not deserialize your trained model.
Maybe this would help: https://stackoverflow.com/a/53689541

**Comment by harishchennupati** [comment]
Thanks Bro it worked

**Comment by mtobeiyf** [comment]
Glad to know it worked 😃
